version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000/items
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
